version: '3.8'

services:
  system-monitor:
    build: Dockerfile
    image: system-monitor
    container_name: system-monitor
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/monitoring/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s